### PR TITLE
Adds support to specify a TFS project collection directly

### PR DESCRIPTION
**Pull request by jgressmann**
Depending on the user account used to access TFS browsing for project
collections may no be permitted. This change enables the user to specify the
project collection during TFS server configuration. The collection
name is stored alongside user name/password/server url in the CI
settings.

### CODE REVIEW

**Comment by lprichar** [comment]
Dude, @jgressmann, this looks awesome!  This should fix Issue #88 and Issue #82 and was the next bug in my queue.  Thank you!  Will test it out tonight.

**Comment by lprichar** [comment]
Worked beautifully, thanks again @jgressmann

**Comment by jgressmann** [comment]
My pleasure!

**Comment by spam1923** [comment]
Thank you this solved my problems. Works great! @jgressmann

**Pull request merged**
