### PR TITLE
Fixes an issue with SOS trashing the settings file

### PR DESCRIPTION
**Pull request by jgressmann**
Sometimes the config file would get deleted and no new config file would be in its place. This change first writes the new config file to disk, then replaces the old one.

### CODE REVIEW

**Comment by jgressmann** [comment]
It looks like a race condition all right. 
I attached to relevant part of the log file (no errors prior to the ones in the snippet).
My guess is the change works for me because moves are atomic in NTFS.
[sos-config-file-trash.txt](https://github.com/AutomatedArchitecture/SirenOfShame/files/1060538/sos-config-file-trash.txt)

**Comment by lprichar** [comment]
That totally makes sense, thanks for clarifying and for finding a fix.  It's interesting that this project has been around a long time and no one else has discovered this issue.  I'm wondering if it's somehow related to async/await code in the new TFS plugin, and the GetBuildsStatuses(...).Result call in particular in the TfsRestWatcher.cs.

I guess what I'm saying is I'm worried that we're addressing the symptoms and not the cause, and wondering if the underlying issue here will result in other bugs and we'll end up with a lot of patching up type code.

But I guess until we figure that out we need to fix this bug, so I'll merge it, but maybe we can revert at some point if we discover the true cause.  Long story short: thanks again for your help :).

**Comment by lprichar** [comment]
Hey @jgressmann I just put out v2.4.10 which was almost exclusively contributions from you.  Do you have a twitter handle or something I can thank you @?

**Comment by jgressmann** [comment]
Hi Lee,

just my e-mail won't do?

Cheers,
Jean

**Pull request merged**
