### PR TITLE
Check if user is present in leader list before adding

### PR DESCRIPTION
**Pull request by JohanO**
Fix Issue #79

### CODE REVIEW

**Comment by lprichar** [comment]
Funny, this issue came up in issue #67 and I thought I'd fixed it further upstream.  I'd still kind of prefer to fix it earlier in the pipeline (i.e. in the RulesEngine) to ensure it doesn't affect other components.  Since I can't reproduce I'm more than  happy to merge in this contribution, but @JohanO, if you can consistently reproduce would you be willing to debug in a little deeper into where the source of the issue is?

**Comment by JohanO** [comment]
I agree, fixing the root cause is better than adding guards in the UI.

I will take a look in the RulesEngine. I don't want to use our "production" build server to debug this issue, so I will have to set up a "debug" build server. Might take a few days.

**Comment by lprichar** [comment]
I understand and really appreciate the help.  It might also be wise to manually back up your settings and history, which you can do by saving/restoring everything in C:\Users\[acct]\AppData\Local\Automated Architecture\SirenOfShame.

Also, if you're building from source you should get a "Mock" CI server that shows up and pops up a little mock dialog.  It's possible that might help avoid setting up a new build server.

Finally, the last unit test I wrote to help track this down was RulesEngineTest/DuplicateUsersInCheckin_OnlyOneNewUserEvent().  Might help, might not.  I wish I could reproduce.  Thanks again, Lee.

**Comment by JohanO** [comment]
Managed to reproduce using the Mock CI server! Thanks for your help.
I will look into the RulesEngine and try to fix the problem now.

**Comment by lprichar** [comment]
Nice!  I still don't understand why it works 99% of the time.  I mean, that code is being hit on every check-in, right?  But we don't see duplicated users on every check-in (or at least I don't).  Did you get a chance to look at the RulesEngineTest/DuplicateUsersInCheckin_OnlyOneNewUserEvent() test?  Were you able to write a similar failing test to cover why it was happening prior to the fix?  I've been trying to keep the rules engine code 100% TDD.  I don't mind writing the test for this case, but I'm still a little unclear on under what circumstances the check all existing users code you wrote would be solving the problem.

**Comment by JohanO** [comment]
The problem occurs only the very first time you check-in on a new build. All other check-ins to that build works fine. Like this:
1. You check-in for the first time to build A. You are added to the list of leaders. This is correct.
2. You check-in for the first time to build B. You are added again to the list of leader. This is the bug.
3. You continue to check-in to build A and build B. Only the score is updated in the list. You are not added.

My change verifies that the user who did the check-in does not already exist in another build. If the user exist he should already be added to the list of leaders and we do not have to call InvokeNewUser. If the user does not exist in any other build, then this is truly a new user, who we have never seen before, and we have to call InvokeNewUser. 

Regarding TDD:
I wrote a test case, "UsersFirstCheckinOnOtherBuild_NoNewUserEvent", that failed. Then I made the changes to RulesEngine and the test passed. All other tests pass, so my change should be safe to merge.

**Comment by lprichar** [comment]
Beautiful, thank you!

**Pull request merged**
