### PR TITLE
support teamcity 10.0.4

### PR DESCRIPTION
**Pull request by iamkrillin**

### CODE REVIEW

**Comment by lprichar** [comment]
Thanks so much @iamkrillin! Will this still support prior versions of TeamCity?

**Comment by iamkrillin** [comment]
I don't have any prior versions to test with

**Comment by lprichar** [comment]
I'll test it tonight.  If it doesn't work I guess we'll have to do something to determine which code branch to take since I'd like to maintain backwards compatiblity.

**Comment by iamkrillin** [comment]
put another fix in to show the users name from TeamCity when a build is triggered manually

**Comment by iamkrillin** [comment]
I think that may be #68

**Comment by lprichar** [comment]
It looks like the changes in this PR broke the unit test 'TeamCityFailureDueToCleanup'. Would you mind taking a look over my fix: https://github.com/AutomatedArchitecture/SirenOfShame/commit/3e2f60f19a138742b9a697e99f19fe2450112e8a.  I can submit as a PR to your PR if you like (I think you can do that, right?).

On that topic, would you be willing to write a unit test for Team City 10.0.4 along the lines of TeamCityBuildStatus_PassingBuildNoComment?  Getting raw build output along the lines of TeamCityFailingBuild.xml is invaluable in reducing regressions and maintaining backwards compatibility.

**Comment by lprichar** [comment]
This works perfectly with TeamCity 8.0.4!  Let me know if you're game for writing a quick unit test for 10.0.4 and I'll get it merged over and created an official build.

**Comment by iamkrillin** [comment]
There ya go, I also moved the teamcity resources into its own folder and added all the relevent xml docs for 10.0.04

**Comment by lprichar** [comment]
lol "someonebroke the build and I am very sad".  Thank you so much @iamkrillin this looks awesome!

**Pull request merged**
