### PR TITLE
Moved scrollbar on leader list so it won't hide stats.

### PR DESCRIPTION
**Pull request by JohanO**
Fix Issue #77

### CODE REVIEW

**Comment by lprichar** [comment]
Hey JohanO, thanks so much for all the recent contributions!  Everything looks pretty good on this fix, however it looks like I'm getting some new screen clipping issues on the people detail page:

image

Are you seeing that in your environment?

**Comment by JohanO** [comment]
Oh, I didn't notice that one, but yes, I am seeing that as well.
I increased the size of the list of leaders to make room for the scrollbar. Thats probably the cause of the clipping. I will look into it.

**Comment by JohanO** [comment]
The Designer in Visual Studio are playing trix on me. I reverted my previous change and hand coded the .designer.cs files. Now it looks much better.

**Comment by lprichar** [comment]
Sorry, forgot to merge this in.  Thanks so much @JohanO!

**Pull request closed without merging**
